apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"key":"black-app"},"name":"mr-black","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"key":"black-app"}},"template":{"metadata":{"labels":{"key":"black-app"}},"spec":{"containers":[{"image":"docker.io/library/nginx:1.16","name":"black-app","ports":[{"containerPort":5645}]}]}}}}
  creationTimestamp: "2024-08-06T09:44:03Z"
  generation: 1
  labels:
    key: black-app
  name: mr-black
  namespace: default
  resourceVersion: "11215"
  uid: 44758ef9-4aec-4e6b-8450-f373ce37e75f
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      key: black-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        key: black-app
    spec:
      containers:
      - image: docker.io/library/nginx:1.16
        imagePullPolicy: IfNotPresent
        name: black-app
        ports:
        - containerPort: 5645
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2024-08-06T09:44:14Z"
    lastUpdateTime: "2024-08-06T09:44:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-08-06T09:44:03Z"
    lastUpdateTime: "2024-08-06T09:44:14Z"
    message: ReplicaSet "mr-black-7c6b98f888" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
